language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

env:
  matrix:
    - PROFILE=2.0
    - PROFILE=2.1
    - PROFILE=2.1-spring31

install: true
script: "mvn -P ${PROFILE} clean compile test"
